name: run groups.py

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Group Sizes'
        required: true
        default: '2'
        type: choice
        options:
        - '2'
        - '3'
        - '4'
        - '5'
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - name: run groups.py
        run: python ./pairing/rnd_groups.py
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}
      - name: commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "update groups.csv"
          author_name: "github-actions"
          author_email: "actions@github.com"
          push: true